import dotenv from 'dotenv'
dotenv.config()

const JWT_CFG = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  EXPIRES_ACCESS_TOKEN: process.env.EXPIRES_ACCESS_TOKEN,
  EXPIRES_ACCESS_TOKEN_MILLISECONDS: process.env.EXPIRES_ACCESS_TOKEN_MILLISECONDS,
  EXPIRES_REFRESH_TOKEN: process.env.EXPIRES_REFRESH_TOKEN,
  EXPIRES_REFRESH_TOKEN_MILLISECONDS: process.env.EXPIRES_REFRESH_TOKEN_MILLISECONDS,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET
}

export default JWT_CFG
