export { default as logo } from '../../src/assets/img/logo.svg'
export { default as close } from '../../src/assets/img/close.svg'
export { default as open } from '../../src/assets/img/menu.svg'
export { default as add } from '../../src/assets/img/add.svg'
export { default as remove } from '../../src/assets/img/delete.svg'
export { default as edit } from '../../src/assets/img/edit.svg'
